# This is a basic workflow to help you get started with Actions

name: "NPM Publish"

# Controls when the action will run. Triggers the workflow on pull request
# events but only for the master branch
on:
  push:
    branches: [ develop ]

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v1
        with:
          node-version: 14

      - run: npm install

      - uses: JS-DevTools/npm-publish@v1
        with:
          token: ${{ secrets.NPM_PUBLISH_TOKEN }}
